### ISSUE TITLE
Developer Guide

### ISSUE THREAD

**Issue by Jackimaru96** [CS2103-AY1819S2-W17-3/main#14]
# Milestone v1.1
## Developer Guide

-  Similar to the User Guide, start moving the content from your Developer Guide (draft created in previous weeks) into the Developer Guide page in your team repository.
    - @JeremyLoye, @Jackimaru96, @eugeneyl 
        - Design, Architecture  
    - @geezlouisee, @kjiaxuan, @Jackimaru96 
        - Appendix A: Product Scope
        - Appendix B: User Stories
        - Appendix C: Use Cases
        - Appendix D: Non Functional Requirements
        - Appendix E: Glossary
        - Appendix F: Product Survey
        - Appendix G: instructions for Manual Testing

**Comment by geezlouisee** [comment]
- Updated Appendices A, B and C during week 6
- @kjiaxuan updated appendices D, E and F during week 6
- Did some formatting changes during recess week

**Comment by Jackimaru96** [comment]
# Updated Use Cases (Appendix C)
- Please check to see if there are any more possible use cases to be added as well as if there are any errors on my part. 
    - @geezlouisee 
    - @JeremyLoye 
    - @kjiaxuan 
    - @eugeneyl

**Comment by eugeneyl** [comment]
- Updated design component of developer guide, including diagrams and write up.

**Comment by Jackimaru96** [comment]
### User Guide
- Updated User Guide with `description` command usage
