### ISSUE TITLE
Vague invalid command instruction for "set" 

### ISSUE THREAD

**Issue by chiuyuhua** [CS2103-AY1819S2-W17-3/main#149]
I typed in "set $/$100" and received the invalid command display "Amount is positive number, with either 2 decimal place or none", but $100 is no decimal place.

Reproduce behavior:
1. Type "set $/$100" in command box

![image](https://user-images.githubusercontent.com/38231274/55607339-83487280-57ae-11e9-9fa4-f8db156f4f56.png)

**Comment by Jackimaru96** [comment]
Hi, you're not supposed to put a `$` after '$/` :))
