### ISSUE TITLE
"set" command is not working

### ISSUE THREAD

**Issue by chiuyuhua** [CS2103-AY1819S2-W17-3/main#150]
"set" command is not working regardless of any correct number input.

Reproduce behavior:
1. Type "set $/$500.50" in the command box (as given by the example).

![image](https://user-images.githubusercontent.com/38231274/55607457-d3bfd000-57ae-11e9-82ed-5938f48024cc.png)

**Comment by Jackimaru96** [comment]
Hi, again, you're not supposed to put a '$' behind '$/'

**Comment by chiuyuhua** [comment]
sorry i posted on the wrong place just now hahaha, it was the example in the result display for set command that was misleading

**Comment by Jackimaru96** [comment]
Ahh i see! Thats our bad! Thanks for pointing it out!
