### ISSUE TITLE
Refactor: Remove Contact, Address and Email Fields

### ISSUE THREAD

**Issue by Jackimaru96** [CS2103-AY1819S2-W17-3/main#52]
## Refactoring 

Remove:
- [x] Contact
- [x] Address
- [x] Email
- [x] Ensure all other fields are relevant for Finance Log

*** please add on if there are more tasks to be done

@JeremyLoye

**Comment by JeremyLoye** [comment]
Removed Address, Email and Phone fields in:
- Main code
- Test Cases
- Comments
