### ISSUE TITLE
Refactor: Tags to Category

### ISSUE THREAD

**Issue by Jackimaru96** [CS2103-AY1819S2-W17-3/main#53]
# Refactor: Tags to Category

- [x] Refactored Tags to Category
- [x] Updated related tests for refactored class

*** please add on if there are more tasks to be done
@geezlouisee

**Comment by geezlouisee** [comment]
#50 #59 
- Refactoring is mostly done and test cases have mostly been updated, but still have some files where I did not look through the details yet. Will edit them and finalise by milestone v1.2.
  - Tests: Categories listed are still the old "tags" (ie. Have not updated test categories to "Food",
     "Shopping" etc.)
  - Have not changed the "tags" in xml files yet, not sure if they will be affected though
