### ISSUE TITLE
Refactor: Person to Entry

### ISSUE THREAD

**Issue by Jackimaru96** [CS2103-AY1819S2-W17-3/main#54]
# Refactor: Person to Record

- [x] Refactor Person to Record
- [x] Update related tests
- [x] Rename `person` directory under `java\seedu.address\model` to `record`

*** please add on if there are more tasks to be done

@eugeneyl

**Comment by eugeneyl** [comment]
Added Jeremy and Jack as reviewer. Will add it to close after review is done.
