### ISSUE TITLE
Refactor: renaming directories, relevant file directory

### ISSUE THREAD

**Issue by Jackimaru96** [CS2103-AY1819S2-W17-3/main#55]
# Refactor: rename directories

- [x] `seedu.address` to `seedu.finance` or `seedu.expense`
- [x] Under `java.seedu.address.model.util`, rename to relevant names; e.g. AddressBook to FinanceLog etc.
- [x] Same as above for `java.seedu.address.storage`
- [x] Rename the tests as well

*** please add more tasks if you have
@kjiaxuan

**Comment by kjiaxuan** [comment]
#61
