### ISSUE TITLE
Budget Increase, Decrease and Display

### ISSUE THREAD

**Issue by JeremyLoye** [CS2103-AY1819S2-W17-3/main#86]
- [x] Allow SetCommand to set multiple budgets and adjust allocate accordingly.
- [x] Implement logic to decrease current budget when `Records` are added
- [x] Display current and total budget of Finance Tracker in UI
- [x] Add Json versions of CategoryBudget and TotalBudget to store budget data in json files
- [x] Additional test cases for Budget

Free to add any other related features

**Comment by Jackimaru96** [comment]
Removed `increase` implementation
